
GET http://localhost:3333

###
POST http://localhost:3333/assets
Content-Type: application/json

{
    "id": "asset2",
    "symbol": "ITB4",
    "price": 15.00
}

###
GET http://localhost:3333/assets

###
GET http://localhost:3333/wallets

###
POST http://localhost:3333/wallets
Content-Type: application/json

{
    "id": "wallet2"
}

###
GET http://localhost:3333/wallets/wallet1/assets

###
POST http://localhost:3333/wallets/wallet2/assets
Content-Type: application/json

{
    "asset_id": "asset2",
    "shares": 300
}


//Relacionamentos e ordes

###
POST http://localhost:3333/wallets/wallet1/orders
Content-Type: application/json

{
    "asset_id": "asset1",
    "wallet_id": "wallet1",
    "shares": 10,
    "price": 19.00,
    "type": "BUY"
}

###
GET http://localhost:3333/wallets/wallet1/orders

###
POST http://localhost:3000/wallets/wallet1/orders/execute
Content-Type: application/json

{
    "order_id": "649773d3b3af00cbe1817dec",
    "status": "CLOSED",
    "related_investor_id": "xxxx",
    "broker_transaction_id": "xxxx",
    "negotiated_shares": 10,
    "price": 15
}
