version: '3'

services:
  app:
    build: .
    container_name: trade-api
    ports:
      - 3333:3333
      - 5555:5555
    volumes:
      - .:/home/node/app
    # extra_hosts:
    #   - "host.docker.internal:172.24.0.1"
    networks:
      - internal-app-network

  # db:
  #   image: bitnami/mongodb:5.0.17
  #   container_name: db
  #   volumes:
  #     - mongodb_data:/bitnami/mongodb
  #   environment:
  #     MONGODB_ROOT_PASSWORD: root
  #     MONGODB_REPLICA_SET_MODE: primary
  #     MONGODB_REPLICA_SET_KEY: 123456
  #     MONGODB_DATABASE: nest
  #   ports:
  #     - 27017:27017
  #   # networks:
  #   #   - internal-app-network

volumes:
  mongodb_data:
    driver: local
networks:
  internal-app-network:
    driver: bridge
